swagger: '2.0'
info:
  title: hotdoggies API
  description: hotdoggies API
  version: 1.0.0
host: api.hotdoggies.stamer.demo.altostrat.com
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/hotdoggies"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "hotdoggies"
security:
  - firebase: []
paths:
  /events:
    post:
      summary: Post an event
      security:
        - firebase: []
      operationId: post-events
      x-google-backend:
        address: https://hotdoggies-ingest-34td3b3ada-ew.a.run.app/
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /dogs:
    get:
      summary: List all dogs
      security:
        - firebase: []
      operationId: list-dogs
      x-google-backend:
        address: https://hotdoggies-dogs-34td3b3ada-ew.a.run.app/
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /dogs/{key}:
    get:
      summary: Get a specific dog referenced by its key.
      security:
        - firebase: []
      parameters:
        - in: path
          name: key
          type: string
          required: true
          description: Key of the dog to get
      operationId: get-dogs
      x-google-backend:
        address: https://hotdoggies-dogs-34td3b3ada-ew.a.run.app/
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
